export const repositoriesActionTypes = {
    FETCH_REPOSITORIES: 'FETCH_REPOSITORIES',
    FETCH_REPOSITORIES_SUCCESS: 'FETCH_REPOSITORIES_SUCCESS',
    FETCH_REPOSITORIES_ERROR: 'FETCH_REPOSITORIES_ERROR',
    GET_REPOSITORIES_PENDING: 'GET_REPOSITORIES_PENDING',
    GET_REPOSITORIES_SUCCESS: 'GET_REPOSITORIES_SUCCESS',
    GET_REPOSITORIES_ERROR: 'GET_REPOSITORIES_ERROR',
}
export const splashscreenActionType = {
    SET_SPLASHSCREEN_SHOWN: 'SET_SPLASHSCREEN_SHOWN'
}

export const SEARCH_ROUTE = '/'
export const REPO_ROUTE = '/repository'